### ISSUE TITLE
Add Doubly Linked List

### ISSUE THREAD

**Issue by bmcculley** [theuhbis/py-dsa#1]
Task: Create a Doubly Linked List Data Structure

It should have the following methods:

- is_empty
- insert (at index)
- push_back
- push_front
- remove (at index)
- pop_back
- pop_front
- reverse

Add tests to make sure all methods work correctly.

**Comment by user76135** [comment]
@bmcculley I would like to try this one.

**Comment by bmcculley** [comment]
Looks good, thank you
