### ISSUE TITLE
Add Queue Data Structure

### ISSUE THREAD

**Issue by bmcculley** [theuhbis/py-dsa#2]
Task: Create a Queue Data Structure

It should contain the following methods:

- enqueue
- dequeue
- is_empty
- peek

Add tests to make sure all methods work correctly.

**Comment by akhilender-bongirwar** [comment]
Hi @bmcculley, I would like to do this. Please assign me.

**Comment by dNhunter3107** [comment]
I would like to do the task, please assign me.

**Comment by Niiola** [comment]
I would love to be assigned this task
